[package]
name = "gear-book"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.4", features = ["derive", "cargo"] }
thiserror = "1.0.38"
anyhow = "1.0.69"

[dev-dependencies]
rstest = "0.16.0"
