services:
  jaeger:
    image: jaegertracing/all-in-one:1.56
    restart: always
    ports:
      - "16686:16686"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.99.0
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1777:1777" # pprof extension
      - "4317:4317" # OTLP gRPC receiver
      - "13133:13133" # health check extension
      - "55679:55679" # zpages extension
