receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:

exporters:
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

extensions:
  health_check:
  pprof:
    endpoint: :1777
  zpages:
    endpoint: :55679

service:
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - otlp/jaeger
  extensions:
    - pprof
    - zpages
    - health_check
