name: CI

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy, llvm-tools-preview
      - uses: Swatinem/rust-cache@v2
      - name: Run formatter
        run: cargo fmt --all --check
      - name: Run linter
        run: cargo clippy --no-deps -- -D warnings
      - name: Run build
        run: cargo build --workspace
      - name: Install test tools
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest, cargo-llvm-cov
      - name: Run test
        run: cargo llvm-cov nextest --workspace --lcov --output-path lcov.info
      - uses: codecov/codecov-action@v4
        if: matrix.os == 'ubuntu-latest'
        with:
          files: ./lcov.info
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
      - uses: coverallsapp/github-action@v2
        if: matrix.os == 'ubuntu-latest'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./lcov.info
