name: CI

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy, llvm-tools-preview
      - uses: Swatinem/rust-cache@v2
      - name: Run formatter
        run: cargo fmt --all --check
      - name: Run linter
        run: cargo clippy --no-deps -- -D warnings
      - name: Run build
        run: cargo build --workspace
      - name: Install test tools
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest, cargo-llvm-cov
      - name: Run test
        run: cargo llvm-cov nextest --workspace --lcov --output-path lcov.info
